{
 "title": "Network Latency and Bandwidth",
 "description": "Latency statistics from MTR, Bandwith from Speedtest.net",
 "tags": [
  "mtr",
  "influxdb",
  "speedtest"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Worst Latency",
   "type": "stat",
   "description": "Max latency of any hop",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "select": [
      [
       { "params": [ "worst" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worst Latency By Hop",
   "type": "graph",
   "description": "Worst Max Latency per Hop",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_hop]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "query": "SELECT mean(\"worst\") FROM \"mtr\" WHERE $timeFilter GROUP BY time($__interval), \"hop\" fill(previous)",
     "select": [
      [
       { "params": [ "worst" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Hop 1 Loss %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "select": [
      [
       { "params": [ "loss_perc" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Hop 2 Loss %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "select": [
      [
       { "params": [ "loss_perc" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Hop 3 Loss %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "select": [
      [
       { "params": [ "loss_perc" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Hop 4 Loss %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "select": [
      [
       { "params": [ "loss_perc" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "Loss % by hop",
   "type": "table",
   "description": "Packet Loss % by Hop",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "[[tag_hop]] -- [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "hop" ], "type": "tag" }
     ],
     "measurement": "mtr",
     "query": "SELECT max(\"loss_perc\") FROM \"mtr\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "loss_perc" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stdev By Hop",
   "type": "graph",
   "description": "Max Stdev of latency by hop",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_hop]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mtr",
     "query": "SELECT mean(\"worst\") FROM \"mtr\" WHERE $timeFilter GROUP BY time($__interval), \"hop\" fill(previous)",
     "select": [
      [
       { "params": [ "stdev" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Download Bandwidth",
   "type": "gauge",
   "description": "From Speedtest, current download bandwidth",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Bandwidth",
   "type": "gauge",
   "description": "From Speedtest, current download bandwidth",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}