apiVersion: 1
datasources:
- orgId: 1
  name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password: admin
  user: admin
  database: cribl
  basicAuth: false
  isDefault: true
  jsonData:
    httpMode: GET
    keepCookies: []
  readOnly: false